.ci/buildAll.bat
.ci/buildAll.sh

This is mainly intended for CI usage.

Add convenience scripts to build all individual apps

---

.ci/buildAll.bat
.ci/buildAll.sh
.ci/preInstall.sh
.travis.yml

Just some quoting and wording improvements. Thanks to @abdullahselek for the [idea](https://github.com/heremaps/here-ios-sdk-examples/pull/6) to use `travis_wait` for the SDK download.

Miscellaneous minor improvements to the CI scripts

---

turn-by-turn-navigation-android/app/src/main/java/com/here/android/example/guidance/MapFragmentView.java

Remove inaccurate comment in Android TBT sample app

---

geocoder-and-reverse-geocoder-android/app/src/main/java/com/here/android/example/geocoding/MainView.java
map-downloader-android/app/src/main/java/com/here/android/example/map/downloader/MapListView.java

Reverts heremaps/here-android-sdk-examples#40 as it uses an unreleased API.

Revert "Removed usage of deprecated API"

---

urban-mobility-android/app/src/main/java/com/here/android/example/urbanmobility/MapFragmentView.java
urban-mobility-android/app/src/main/res/layout/activity_main.xml

Remove Departure Board Request feature in UM sample app as premium SDK

---

.github/SUPPORT

For the GitHub feature see
https://github.com/blog/2400-support-file-support

Add a SUPPORT file to direct non-commercial users to StackOverflow

---

README.md

Fix references to directory names

---

map-rendering/app/src/main/java/com/here/android/example/map/basic/MapFragmentView.java

as per request https://github.com/heremaps/here-android-sdk-examples/issues/100

Set the default map center to Vancouver in Map Rendering app

---

turn-by-turn-navigation/app/build.gradle
turn-by-turn-navigation/app/src/main/AndroidManifest.xml
turn-by-turn-navigation/app/src/main/java/com/here/android/example/guidance/ForegroundService.java
turn-by-turn-navigation/app/src/main/java/com/here/android/example/guidance/MainActivity.java
turn-by-turn-navigation/app/src/main/java/com/here/android/example/guidance/MapFragmentView.java
turn-by-turn-navigation/build.gradle

Added foreground service

---

speed-limit-watcher/README.md

Signed-off-by: Mariusz Karpicki <mkarpicki@gmail.com>

[SpeedLimitWatcher] Updated links to documentation

---

3DModel/README.md
3d-venues-and-indoor-routing/README.md
3d-venues-and-indoor-routing/app/src/main/java/com/here/android/example/venue/Venue3dActivity.java
advanced-navigation/README.md
geocoder-and-reverse-geocoder/README.md
map-attribute/README.md
map-customization/README.md
map-downloader/README.md
map-gestures/README.md
map-objects/README.md
map-rendering/README.md
positioning-venues-and-logging/README.md
positioning/README.md
route-tta/README.md
routing/README.md
search/README.md
speed-limit-watcher/README.md
turn-by-turn-navigation/README.md

Update project folders with README.md files. Each file includes simple description and documentation references

Added README files for nested projects

---

map-objects/app/src/main/java/com/here/android/example/map/objects/MainActivity.java
map-objects/app/src/main/java/com/here/android/example/map/objects/MapFragmentView.java
map-objects/app/src/main/res/layout/activity_main.xml

Add example that shows how to navigate to the set of geo coordinates so they are all in the visible viewport, also padding can be applied to the viewport.

Add sample how zoomTo to set of GeoCoordinates

---

positioning-venues-and-logging/app/src/main/java/com/here/android/example/venuesandlogging/BasicVenueActivity.java
positioning-venues-and-logging/app/src/main/java/com/here/android/positioning/helpers/RadioMapLoadHelper.java

Added example of  positioning radio map downloading to positioning venues app.

Added radio map downloading to example

---

positioning-venues-and-logging/app/src/main/java/com/here/android/example/venuesandlogging/BasicVenueActivity.java
positioning-venues-and-logging/app/src/main/res/layout/activity_main.xml
positioning-venues-and-logging/app/src/main/res/menu/menu.xml
positioning-venues-and-logging/app/src/main/res/values/strings.xml

Example of using routing APIs with HERE positioning.

Added routing example

---

geocoder-and-reverse-geocoder/app/src/main/java/com/here/android/example/geocoding/MainView.java

removed error dialog in case map engine is initialised without error

Removed error dialog when geocoder-and-reverse-geocoder is sucessfully initialized

---

README.md

Update text in README.

---

ftcr/app/src/main/java/com/here/android/example/ftcr/MainActivity.java
ftcr/app/src/main/java/com/here/android/example/ftcr/MapFragmentView.java
ftcr/app/src/main/res/layout/activity_main.xml
ftcr/app/src/main/res/values/strings.xml

Fix ftcr example.

---

advanced-navigation/app/src/main/java/com/here/android/example/advanced/navigation/MapFragmentView.java
advanced-navigation/app/src/main/res/layout/activity_main.xml
turn-by-turn-navigation/app/src/main/java/com/here/android/example/guidance/MapFragmentView.java

1. Show pos indicator. 2. Calculate route on user request.

---

3DModel/app/build.gradle
3d-venues-and-indoor-routing/app/build.gradle
advanced-navigation/app/build.gradle
autoSuggest/app/build.gradle
cle2/app/build.gradle
fleet-connectivity-extension/app/build.gradle
ftcr/app/build.gradle
geocoder-and-reverse-geocoder/app/build.gradle
kotlin-sample/app/build.gradle
map-attribute/app/build.gradle
map-customization/app/build.gradle
map-downloader/app/build.gradle
map-gestures/app/build.gradle
map-objects/app/build.gradle
map-rendering/app/build.gradle
platform-data-extension/app/build.gradle
positioning-on-background/app/build.gradle
positioning-venues-and-logging/app/build.gradle
positioning/app/build.gradle
route-tta/app/build.gradle
routing/app/build.gradle
search/app/build.gradle
speed-limit-watcher/app/build.gradle
turn-by-turn-navigation/app/build.gradle
voice-navigation/app/build.gradle
voice-navigation/app/src/main/AndroidManifest.xml
voice-navigation/app/src/main/java/com/here/android/example/voice/guidance/MapFragmentView.java
voice-navigation/app/src/main/java/com/here/android/example/voice/guidance/VoicePackagesActivity.java

Update target version to 30.

---

fleet-connectivity-extension/app/src/main/java/com/here/tcsdemo/JobDetailsFragment.java
map-downloader/app/src/main/java/com/here/android/example/map/downloader/MainActivity.java
map-downloader/app/src/main/java/com/here/android/example/map/downloader/MapListView.java
map-gestures/app/src/main/java/com/here/android/example/map/gesture/MapFragmentView.java
search/app/src/main/java/com/here/android/example/search/ResultListActivity.java

Fix lint warnings.

---

routing/app/src/main/java/com/here/android/example/routing/MainActivity.java
routing/app/src/main/java/com/here/android/example/routing/MapFragmentView.java
routing/app/src/main/res/layout/activity_main.xml

Show Environmental Zones on map

---

autoSuggest/app/src/main/java/com/here/android/example/autosuggest/MapFragmentView.java
autoSuggest/app/src/main/res/layout/activity_main.xml

Add filtering by country code example.

---

.github/bug_report.md
README.md

Add issue template.

---

routing/app/src/main/java/com/here/android/example/routing/MapFragmentView.java

Add example how to add banned areas for routing.

---

voice-navigation/app/src/main/java/com/here/android/example/voice/guidance/MapFragmentView.java

Show usage of different distance unit for voice guidance.

Set DistanceUnit for voice guidance.

---

advanced-navigation/app/src/main/java/com/here/android/example/advanced/navigation/MapFragmentView.java

Fix exception.

---

3DModel/app/build.gradle
3d-venues-and-indoor-routing/app/build.gradle
advanced-navigation/app/build.gradle
autoSuggest/app/build.gradle
cle2/app/build.gradle
default-navigation-using-ftcr-routing/app/build.gradle
ftcr/app/build.gradle
geocoder-and-reverse-geocoder/app/build.gradle
kotlin-routing-restrictions/app/build.gradle
kotlin-sample/app/build.gradle
map-attribute/app/build.gradle
map-customization/app/build.gradle
map-downloader/app/build.gradle
map-gestures/app/build.gradle
map-objects/app/build.gradle
map-rendering/app/build.gradle
mapdataprefetcher/app/build.gradle
platform-data-extension/app/build.gradle
positioning-on-background/app/build.gradle
positioning-venues-and-logging/app/build.gradle
positioning/app/build.gradle
route-tta/app/build.gradle
route-tta/app/src/main/res/layout/activity_main.xml
routing/app/build.gradle
search/app/build.gradle
speed-limit-watcher/README.md
turn-by-turn-navigation/app/build.gradle
voice-navigation/app/build.gradle

Signed-off-by: kucheria <ext-mariia.kucheriava@here.com>

Fix problem with flatDir

---

mapdataprefetcher/app/build.gradle
speed-limit-watcher/app/build.gradle

Signed-off-by: kucheria <ext-mariia.kucheriava@here.com>

Removed forgotten flatDir
